REVERT!!!! you broke evas build.
evas_object_textblock.c: In function ‘_nodes_next_merge’:
evas_object_textblock.c:380: error: ‘Evas_Object_Textblock_Node’ has no member named ‘len’



git-svn-id: http://svn.enlightenment.org/svn/e/trunk/evas@46874 7cbeb6ba-43b4-40fd-8cce-4c39aea84d33